community_detection:
  method: leiden
  resolution: {min: 0.1, max: 1.0, step: 0.05}
  rng_seed: 12345
  n_restarts: 10
  weight_columns:
    - MechProbLinearDist
    - MechProbPoissonDist
    - LogitProbLinearDist_1.0
    - LogitProbPoissonDist_1.0
network:
  sparsify: {enabled: true, min_edge_weight: 0.01}
  min_edge_weights: [0.0, 0.001, 0.005, 0.01, 0.02, 0.05,  0.1]